slice_name: All Details
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 21__table
  viz_type: pivot_table_v2
  slice_id: 85
  groupbyColumns:
  - Location
  - Category
  - Sub Category
  groupbyRows:
  - Date
  time_grain_sqla: P1D
  temporal_columns_lookup: {}
  metrics:
  - Total Cost
  metricsLayout: COLUMNS
  adhoc_filters: []
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  rowTotals: true
  rowSubTotals: true
  colTotals: true
  colSubTotals: false
  transposePivot: true
  valueFormat: ',d'
  currency_format:
    symbol: INR
    symbolPosition: prefix
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  rowSubtotalPosition: false
  conditional_formatting:
  - colorScheme: '#ACE1C4'
    column: Total Cost
    operator: None
  extra_form_data: {}
  dashboards:
  - 8
query_context: '{"datasource":{"id":21,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["Location","Category","Sub
  Category","Date"],"metrics":["Total Cost"],"orderby":[["Total Cost",false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"21__table","viz_type":"pivot_table_v2","slice_id":85,"groupbyColumns":["Location","Category","Sub
  Category"],"groupbyRows":["Date"],"time_grain_sqla":"P1D","temporal_columns_lookup":{},"metrics":["Total
  Cost"],"metricsLayout":"COLUMNS","adhoc_filters":[],"row_limit":10000,"order_desc":true,"aggregateFunction":"Sum","rowTotals":true,"rowSubTotals":true,"colTotals":true,"colSubTotals":false,"transposePivot":true,"valueFormat":",d","currency_format":{"symbol":"INR","symbolPosition":"prefix"},"date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","rowSubtotalPosition":false,"conditional_formatting":[{"colorScheme":"#ACE1C4","column":"Total
  Cost","operator":"None"}],"extra_form_data":{},"dashboards":[8],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 6b151904-e2bc-489f-8b3e-9f492c92866d
version: 1.0.0
dataset_uuid: 38b186d8-301a-4008-805e-8c27271eaf5c
